name: Engine CI

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "services/engine/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "services/engine/**"
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/engine

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -v ./...
      - name: Build executable
        run: go build -v ./...
      - name: Run vet
        run: go vet -v ./...
