name: Engine CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "services/engine/**"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/engine

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: services/engine/go.mod
          cache: true

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.1020

      - name: Generate templ
        run: templ generate

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

      - name: Build executable
        run: go build -v ./...

      - name: Run vet
        run: go vet -v ./...
